import { describe, expect, it } from "vitest";
import { MermaidAdapter } from "../src/core/mermaidAdapter.js";
import type { ProjectDiagram } from "../src/core/projectDiagram.js";
const diagram = (kind: ProjectDiagram["kind"]): ProjectDiagram => ({ schemaVersion: 1, id: "m", title: "Flow", kind, version: 1, updatedAt: 1, nodes: [{ id: "a/b", label: 'A "quoted"\nlabel', role: kind === "lifecycle" ? "state" : "step", semanticIds: [], evidence: [{ path: "README.md" }] }, { id: "a-b", label: "End", role: "step", semanticIds: [], evidence: [] }], relations: [{ id: "r", from: "a/b", to: "a-b", kind: "flows_to", label: "next", order: 1, evidence: [] }] });
describe("MermaidAdapter", () => {
  it.each([["architecture", "flowchart TD"], ["workflow", "flowchart TD"], ["data_flow", "flowchart LR"], ["sequence", "sequenceDiagram"], ["lifecycle", "stateDiagram-v2"]] as const)("uses native syntax for %s", async (kind, header) => { const adapter = new MermaidAdapter(); const doc = await adapter.transform(diagram(kind)); expect((await adapter.export(doc, { format: "mermaid" })).content).toContain(header); });
  it("sanitizes colliding IDs and labels deterministically", async () => { const adapter = new MermaidAdapter(); const doc = await adapter.transform(diagram("workflow")); const first = (await adapter.render(doc)).content; expect(first).toBe((await adapter.render(doc)).content); expect(first).toContain("A &quot;quoted&quot; label"); expect(first).toContain("a_b["); expect(first).toContain("a_b_2["); expect(first).not.toMatch(/\n\s*end\[/); });
  it("rejects unsupported formats and document versions", async () => { const adapter = new MermaidAdapter(); const doc = await adapter.transform(diagram("workflow")); await expect(adapter.export(doc, { format: "svg" })).rejects.toThrow("cannot export"); await expect(adapter.render({ ...doc, adapterVersion: "0" })).rejects.toThrow("version"); expect((await adapter.validate({ ...doc, adapterVersion: "0" })).status).toBe("failed"); });
});
