import { BUILTIN_METHODS } from "./builtins.js";
import { formatFieldType, methodResultType } from "./methodSignature.js";
import type { FieldDefinition, RegisteredCallable } from "./types.js";

const byId = new Map(BUILTIN_METHODS.map((definition) => [definition.id, { ...definition, source: "builtin" as const }]));
const CONVERSATION_METHODS = new Set(["agent", "ask", "plan"]);

export function builtinApiDefinition(id: string): RegisteredCallable | undefined {
  return byId.get(id);
}

/** A namespace exists when at least one built-in API is below it. */
export function builtinApiNamespace(id: string): boolean {
  return [...byId.keys()].some((candidate) => candidate.startsWith(`${id}.`));
}

export function isBuiltinApiTarget(id: string): boolean {
  return Boolean(builtinApiDefinition(id)) || builtinApiNamespace(id);
}

export interface BuiltinApiDocument {
  text: string;
  ranges: ReadonlyMap<string, { from: number; to: number; nameFrom: number; nameTo: number }>;
}

interface NamespaceNode {
  methods: RegisteredCallable[];
  children: Map<string, NamespaceNode>;
}

function describeField(field: FieldDefinition): string {
  const optional = field.required ? "" : " (optional)";
  const defaultValue = field.default === undefined ? "" : `; default: ${JSON.stringify(field.default)}`;
  return `#   ${field.name}: ${formatFieldType(field)}${optional}${defaultValue}${field.description ? ` — ${field.description}` : ""}`;
}

function definitionType(field: FieldDefinition): string {
  return formatFieldType(field)
    .replace(/\bstring\b/g, "str")
    .replace(/\bboolean\b/g, "bool")
    .replace(/\bobject\b/g, "dict")
    .replace(/\bstr\[\]/g, "list[str]");
}

function definitionDefault(field: FieldDefinition): string {
  if (typeof field.default === "string") return JSON.stringify(field.default);
  if (typeof field.default === "boolean") return field.default ? "True" : "False";
  return JSON.stringify(field.default);
}

function apiTree(): NamespaceNode {
  const root: NamespaceNode = { methods: [], children: new Map() };
  for (const method of byId.values()) {
    const parts = method.id.split(".");
    const leaf = parts.pop();
    if (!leaf) continue;
    let node = root;
    for (const part of parts) {
      let child = node.children.get(part);
      if (!child) {
        child = { methods: [], children: new Map() };
        node.children.set(part, child);
      }
      node = child;
    }
    node.methods.push(method);
  }
  return root;
}

/** Render every stable built-in API, following their public namespace hierarchy. */
export function builtinApiDocument(): BuiltinApiDocument {
  let text = "# Dext Built-in APIs\n# This read-only reference is generated by the Dext extension.\n\n";
  const ranges = new Map<string, { from: number; to: number; nameFrom: number; nameTo: number }>();
  const write = (value: string): void => { text += value; };
  const indent = (depth: number): string => "    ".repeat(depth);

  const renderMethod = (method: RegisteredCallable, name: string, depth: number): void => {
    const from = text.length;
    const prefix = indent(depth);
    write(`${prefix}# ${method.title}\n${prefix}# ${method.description}\n${prefix}# API: ${method.id}\n`);
    const visibleInput = CONVERSATION_METHODS.has(method.id) ? method.input : method.input.filter((field) => !field.internal);
    if (visibleInput.length) {
      write(`${prefix}# Parameters:\n`);
      for (const field of visibleInput) write(`${prefix}${describeField(field)}\n`);
    }
    const nameFrom = text.length + prefix.length + "def ".length;
    write(`${prefix}def ${name}(\n`);
    for (const field of visibleInput) {
      const defaultValue = field.default === undefined ? "" : ` = ${definitionDefault(field)}`;
      write(`${indent(depth + 1)}${field.name}: ${definitionType(field)}${defaultValue},\n`);
    }
    write(`${prefix}) -> ${methodResultType(method)}:\n${indent(depth + 1)}...\n`);
    const fields = method.output.fields ?? [];
    if (fields.length) {
      write(`${prefix}# ${methodResultType(method)} fields:\n`);
      for (const field of fields) write(`${prefix}${describeField(field)}\n`);
    }
    write("\n");
    ranges.set(method.id, { from, to: text.length - 1, nameFrom, nameTo: nameFrom + name.length });
  };

  const renderNamespace = (node: NamespaceNode, id: string, name: string, depth: number): void => {
    const from = text.length;
    const prefix = indent(depth);
    const nameFrom = text.length + prefix.length + "class ".length;
    write(`${prefix}# Namespace: ${id}\n${prefix}class ${name}:\n`);
    const bodyStart = text.length;
    for (const method of [...node.methods].sort((left, right) => left.id.localeCompare(right.id))) {
      renderMethod(method, method.id.split(".").at(-1)!, depth + 1);
    }
    for (const [childName, child] of [...node.children].sort(([left], [right]) => left.localeCompare(right))) {
      renderNamespace(child, `${id}.${childName}`, childName, depth + 1);
    }
    if (text.length === bodyStart) write(`${indent(depth + 1)}...\n`);
    write("\n");
    ranges.set(id, { from, to: text.length - 1, nameFrom, nameTo: nameFrom + name.length });
  };

  const root = apiTree();
  for (const method of [...root.methods].sort((left, right) => left.id.localeCompare(right.id))) {
    renderMethod(method, method.id, 0);
  }
  for (const [name, child] of [...root.children].sort(([left], [right]) => left.localeCompare(right))) {
    renderNamespace(child, name, name, 0);
  }
  return { text, ranges };
}

export interface BuiltinApiTarget {
  originFrom: number;
  originTo: number;
  id: string;
}

/** Resolve an API or namespace name in the generated reference document. */
export function builtinApiReferenceTarget(source: string, cursor: number): BuiltinApiTarget | undefined {
  const match = [...source.matchAll(/[A-Za-z_][A-Za-z0-9_.-]*/g)].find((candidate) => {
    const from = candidate.index ?? 0;
    return from <= cursor && cursor <= from + candidate[0].length;
  });
  if (!match) return undefined;
  const from = match.index ?? 0;
  const direct = match[0];
  if (isBuiltinApiTarget(direct)) return { originFrom: from, originTo: from + direct.length, id: direct };

  // Names below a namespace are intentionally rendered as normal Python
  // class/def identifiers (`class url`, `def parse`). Recover their fully
  // qualified public ID from the preceding generated marker.
  const lineStart = source.lastIndexOf("\n", from - 1) + 1;
  const lineEnd = source.indexOf("\n", from);
  const line = source.slice(lineStart, lineEnd < 0 ? source.length : lineEnd);
  if (new RegExp(`^\\s*class\\s+${direct}\\b`).test(line)) {
    const namespace = [...source.slice(0, lineStart).matchAll(/^\s*# Namespace: ([A-Za-z][A-Za-z0-9_.-]*)$/gm)].at(-1)?.[1];
    if (namespace && isBuiltinApiTarget(namespace)) return { originFrom: from, originTo: from + direct.length, id: namespace };
  }
  if (new RegExp(`^\\s*def\\s+${direct}\\b`).test(line)) {
    const api = [...source.slice(0, lineStart).matchAll(/^\s*# API: ([A-Za-z][A-Za-z0-9_.-]*)$/gm)].at(-1)?.[1];
    if (api && isBuiltinApiTarget(api)) return { originFrom: from, originTo: from + direct.length, id: api };
  }
  return undefined;
}
