import { BUILTIN_METHODS } from "./builtins.js";
import { dextOptionsType, dextTsFieldType } from "./dextApiTypes.js";
import { CONVERSATION_METHODS, methodResultType } from "./methodSignature.js";
import type { FieldDefinition, RegisteredCallable } from "./types.js";

const byId = new Map(BUILTIN_METHODS.map((definition) => [definition.id, { ...definition, source: "builtin" as const }]));

export function builtinApiDefinition(id: string): RegisteredCallable | undefined {
  return byId.get(id);
}

/** A namespace exists when at least one built-in API is below it. */
export function builtinApiNamespace(id: string): boolean {
  return [...byId.keys()].some((candidate) => candidate.startsWith(`${id}.`));
}

export function isBuiltinApiTarget(id: string): boolean {
  return Boolean(builtinApiDefinition(id)) || builtinApiNamespace(id);
}

export interface BuiltinApiDocument {
  text: string;
  ranges: ReadonlyMap<string, { from: number; to: number; nameFrom: number; nameTo: number }>;
}

interface NamespaceNode {
  methods: RegisteredCallable[];
  children: Map<string, NamespaceNode>;
}

/** Quote an object or function name that is not a valid TypeScript identifier. */
function memberName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function comment(value: string, prefix: string): string {
  return value.replace(/\r?\n/g, `\n${prefix}// `);
}

function describeField(field: FieldDefinition): string {
  const optional = field.required ? "" : "?";
  const defaultValue = field.default === undefined ? "" : `; default: ${JSON.stringify(field.default)}`;
  return `//   ${field.name}${optional}: ${dextTsFieldType(field)}${defaultValue}${field.description ? ` — ${field.description}` : ""}`;
}

function apiTree(methods: Iterable<RegisteredCallable>): NamespaceNode {
  const root: NamespaceNode = { methods: [], children: new Map() };
  for (const method of methods) {
    const parts = method.id.split(".");
    const leaf = parts.pop();
    if (!leaf) continue;
    let node = root;
    for (const part of parts) {
      let child = node.children.get(part);
      if (!child) {
        child = { methods: [], children: new Map() };
        node.children.set(part, child);
      }
      node = child;
    }
    node.methods.push(method);
  }
  return root;
}

/** Render every stable built-in API, following their public namespace hierarchy. */
export function builtinApiDocument(): BuiltinApiDocument {
  return callableApiDocument(byId.values(), "Dext Built-in APIs");
}

/** Generate the same read-only reference for built-ins and registered MCP tools. */
export function callableApiDocument(methods: Iterable<RegisteredCallable>, title: string): BuiltinApiDocument {
  let text = `// ${title}\n// This read-only reference is generated by the Dext extension.\n`
    + "// Values that cross a `dext` API boundary must be JSON-serializable.\n\n";
  const ranges = new Map<string, { from: number; to: number; nameFrom: number; nameTo: number }>();
  const write = (value: string): void => { text += value; };
  const indent = (depth: number): string => "  ".repeat(depth);

  const renderMethod = (method: RegisteredCallable, name: string, depth: number): void => {
    const from = text.length;
    const prefix = indent(depth);
    write(`${prefix}// API: ${method.id}\n`);
    write(`${prefix}// ${comment(method.title, prefix)} — ${comment(method.description, prefix)}\n`);
    const visibleInput = CONVERSATION_METHODS.has(method.id) ? method.input : method.input.filter((field) => !field.internal);
    if (visibleInput.length) {
      write(`${prefix}// Parameters:\n`);
      for (const field of visibleInput) write(`${prefix}${comment(describeField(field), prefix)}\n`);
    }
    const rendered = memberName(name);
    const keyword = depth === 0 ? "export function " : "";
    const nameFrom = text.length + prefix.length + keyword.length + (rendered.startsWith('"') ? 1 : 0);
    const options = `options: ${dextOptionsType(method)}`;
    const result = `Promise<${methodResultType(method)}>`;
    write(depth === 0
      ? `${prefix}${keyword}${rendered}(${options}): ${result};\n`
      : `${prefix}${rendered}: (${options}) => ${result};\n`);
    const fields = method.output.fields ?? [];
    if (fields.length) {
      write(`${prefix}// ${methodResultType(method)} fields:\n`);
      for (const field of fields) write(`${prefix}${comment(describeField(field), prefix)}\n`);
    }
    write("\n");
    ranges.set(method.id, { from, to: text.length - 1, nameFrom, nameTo: nameFrom + name.length });
  };

  const renderNamespace = (node: NamespaceNode, id: string, name: string, depth: number): void => {
    const from = text.length;
    const prefix = indent(depth);
    write(`${prefix}// Namespace: ${id}\n`);
    const rendered = memberName(name);
    const keyword = depth === 0 ? "export const " : "";
    const nameFrom = text.length + prefix.length + keyword.length + (rendered.startsWith('"') ? 1 : 0);
    write(`${prefix}${keyword}${rendered}${depth === 0 ? " = " : ": "}{\n`);
    const bodyStart = text.length;
    for (const method of [...node.methods].sort((left, right) => left.id.localeCompare(right.id))) {
      renderMethod(method, method.id.split(".").at(-1)!, depth + 1);
    }
    for (const [childName, child] of [...node.children].sort(([left], [right]) => left.localeCompare(right))) {
      renderNamespace(child, `${id}.${childName}`, childName, depth + 1);
    }
    if (text.length === bodyStart) write(`${indent(depth + 1)}// No APIs.\n`);
    write(`${prefix}}${depth === 0 ? ";" : ","}\n\n`);
    ranges.set(id, { from, to: text.length - 1, nameFrom, nameTo: nameFrom + name.length });
  };

  const root = apiTree(methods);
  for (const method of [...root.methods].sort((left, right) => left.id.localeCompare(right.id))) {
    renderMethod(method, method.id, 0);
  }
  for (const [name, child] of [...root.children].sort(([left], [right]) => left.localeCompare(right))) {
    renderNamespace(child, name, name, 0);
  }
  return { text, ranges };
}

export interface BuiltinApiTarget {
  originFrom: number;
  originTo: number;
  id: string;
}

/** Resolve an API or namespace name in the generated reference document. */
export function builtinApiReferenceTarget(source: string, cursor: number): BuiltinApiTarget | undefined {
  const match = [...source.matchAll(/[A-Za-z_][A-Za-z0-9_.-]*/g)].find((candidate) => {
    const from = candidate.index ?? 0;
    return from <= cursor && cursor <= from + candidate[0].length;
  });
  if (!match) return undefined;
  const from = match.index ?? 0;
  const direct = match[0];
  if (isBuiltinApiTarget(direct)) return { originFrom: from, originTo: from + direct.length, id: direct };

  // Names below a namespace are rendered as ordinary object members. Recover
  // their fully qualified public ID from the preceding generated marker.
  const lineStart = source.lastIndexOf("\n", from - 1) + 1;
  const lineEnd = source.indexOf("\n", from);
  const line = source.slice(lineStart, lineEnd < 0 ? source.length : lineEnd);
  const escaped = escapeRegExp(direct);
  if (new RegExp(`^\\s*(?:export const\\s+)?${escaped}\\s*(?:=|:)\\s*\\{`).test(line)) {
    const namespace = [...source.slice(0, lineStart).matchAll(/^\s*\/\/ Namespace: ([A-Za-z][A-Za-z0-9_.-]*)$/gm)].at(-1)?.[1];
    if (namespace && isBuiltinApiTarget(namespace)) return { originFrom: from, originTo: from + direct.length, id: namespace };
  }
  if (new RegExp(`^\\s*(?:export function\\s+)?${escaped}\\s*[(:]`).test(line)) {
    const api = [...source.slice(0, lineStart).matchAll(/^\s*\/\/ API: ([A-Za-z][A-Za-z0-9_.-]*)$/gm)].at(-1)?.[1];
    if (api && isBuiltinApiTarget(api)) return { originFrom: from, originTo: from + direct.length, id: api };
  }
  return undefined;
}
